### PR TITLE
Catch error and display it on UI

### LINKED ISSUE #361: Twig error handling
If twig rendering fails in an email (ex: issue preview), show a graceful error with a helpful error message.

### PR DESCRIPTION
**Pull request by Nolab0**
Close #361 

When intentionally breaking the twig template:
image

### CODE REVIEW

File: backend/src/Service/Template/HtmlTemplateRenderer.php [hunk 1]
```diff
@@ -42,7 +44,11 @@ public function renderFromSend(Send $send): string
 
     public function render(string $template, TemplateVariables $variables): string
     {
-        $template = $this->twig->createTemplate($template);
-        return $template->render((array)$variables);
+        try {
+            $twigTemplate = $this->twig->createTemplate($template);
+            return $twigTemplate->render((array)$variables);
+        } catch (TwigError $e) {
+            throw new UnprocessableEntityHttpException($e->getRawMessage());
```
Comment (supun-io) [inline backend/src/Service/Template/HtmlTemplateRenderer.php]: you can't throw HttpExceptions in services. You have to either (1) simply not catch the TwigError and mark the function throwing that exception, or (2) throw a custom exception. Here, I believe (2) would work better. Then, in the Http controller where this service is used, you have to catch that and throw the Http exception.

**Review by supun-io — APPROVED** [review]
